lint:
  files_exist:
    - conf/modules.config
    - conf/test.config
    - conf/test_full.config
  files_unchanged:
    - .gitignore
    - LICENSE
    - assets/nf-core-rnadnavar_logo_light.png
    - docs/images/nf-core-rnadnavar_logo_dark.png
    - docs/images/nf-core-rnadnavar_logo_light.png
  modules_config: false
  template_strings: false
nf_core_version: 3.5.1
repository_type: pipeline
template:
  author: Raquel Manzano-Garcia
  description: Pipeline for RNA and DNA integrated analysis for somatic mutation detection
  force: false
  is_nfcore: true
  name: rnadnavar
  org: nf-core
  outdir: .
  version: 1.0
