name: maf_filtering
description: Filters MAF file with python script
keywords:
  - filtering
  - MAF
  - variant calling
tools:
  - decompose:
      description: Filters MAF file with python script
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - maf:
      type: file
      description: The MAF file to be filtered
      pattern: "*.{maf.gz,maf}"
  - meta2:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: Input genome fasta file

output[:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - maf:
      type: file
      description: The MAF file to be filtered
      pattern: "*.{maf.gz,maf}"
  - version:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@RaqManzano"
